# Use the latest 2.1 version of CircleCI pipeline process engine.
# https://circleci.com/docs/2.0/configuration-reference
# https://circleci.com/docs/2.0/getting-started/#section=getting-started
version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
